language: php

sudo: false

php:
    - 7.1
    - 7.0
    - 5.6
    - 5.5
    - hhvm

notifications:
    email: deploy@peter-gribanov.ru

matrix:
    fast_finish: true
    include:
        - php: 5.6
          env: SYMFONY_VERSION=2.7.*
        - php: 5.6
          env: SYMFONY_VERSION=2.8.*
        - php: 5.6
          env: SYMFONY_VERSION=3.0.*
        - php: 5.6
          env: DOCTRINE_VERSION=2.4.*
        - php: 5.6
          env: DOCTRINE_VERSION=2.5.*
        - php: 5.6
          env: TWIG_VERSION=1.*
        - php: 7.0
          env: TWIG_VERSION=2.*
    allow_failures:
        - php: hhvm

before_install:
    - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then phpenv config-rm xdebug.ini; fi;
    - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi;
    - if [[ -n "$GH_TOKEN" ]]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
    - composer self-update
    - mkdir build

before_script:
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --dev --no-update; fi;
    - if [ "$DOCTRINE_VERSION" != "" ]; then composer require "doctrine/orm:${DOCTRINE_VERSION}" --dev --no-update; fi;
    - if [ "$TWIG_VERSION" != "" ]; then composer require "twig/twig:${TWIG_VERSION}" --dev --no-update; fi;
    - composer install --prefer-dist --no-interaction --no-scripts --no-progress

script:
    - vendor/bin/phpunit

after_script:
    - vendor/bin/ocular code-coverage:upload --format=php-clover build/coverage-clover.xml
    - vendor/bin/coveralls -v -c .coveralls.yml
