language: php

sudo: false

notifications:
    email: deploy@peter-gribanov.ru

branches:
  except:
    - /^analysis-.*$/

matrix:
    fast_finish: true
    include:
        - php: 7.3
        - php: 7.2
        - php: 7.1
        - php: 7.0
        - php: 5.6
        - php: 5.5
          dist: trusty
        - php: 5.5
          dist: trusty
          env: SYMFONY_VERSION=2.8.*
        - php: 5.5
          dist: trusty
          env: SYMFONY_VERSION=3.4.*
        - php: 7.1
          env: SYMFONY_VERSION=4.2.* PHPUNIT_VERSION=5.7.*
        - php: 7.1
          env: SYMFONY_VERSION=4.3.* PHPUNIT_VERSION=5.7.*
        - php: 5.5
          dist: trusty
          env: DOCTRINE_VERSION=2.4.*
        - php: 5.5
          dist: trusty
          env: DOCTRINE_VERSION=2.5.*
        - php: 7.1
          dist: trusty
          env: DOCTRINE_VERSION=2.6.*
        - php: 5.5
          dist: trusty
          env: TWIG_VERSION=1.*
        - php: 7.0
          env: TWIG_VERSION=2.*
        - php: 7.1
          env: PHPSTAN_VERSION=0.11.* PHPSTAN_PHPUNIT_VERSION=0.9.* PHPUNIT_VERSION=6.3.*

before_install:
    - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;

before_script:
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --dev --no-update; fi;
    - if [ "$DOCTRINE_VERSION" != "" ]; then composer require "doctrine/orm:${DOCTRINE_VERSION}" --dev --no-update; fi;
    - if [ "$TWIG_VERSION" != "" ]; then composer require "twig/twig:${TWIG_VERSION}" --dev --no-update; fi;
    - if [ "$PHPUNIT_VERSION" != "" ]; then composer require "phpunit/phpunit:${PHPUNIT_VERSION}" --dev --no-update; fi;
    - if [ "$PHPSTAN_VERSION" != "" ]; then composer require "phpstan/phpstan:${PHPSTAN_VERSION}" --dev --no-update; fi;
    - if [ "$PHPSTAN_PHPUNIT_VERSION" != "" ]; then composer require "phpstan/phpstan-phpunit:${PHPSTAN_PHPUNIT_VERSION}" --dev --no-update; fi;
    - COMPOSER_MEMORY_LIMIT=-1 composer install --prefer-dist --no-interaction --no-scripts --no-progress

script:
    - if [ "$PHPSTAN_VERSION" != "" ]; then ./vendor/bin/phpstan analyse; fi;
    - vendor/bin/phpunit --coverage-clover build/coverage-clover.xml

after_script:
    - vendor/bin/ocular code-coverage:upload --format=php-clover build/coverage-clover.xml
    - vendor/bin/coveralls -v -c .coveralls.yml
