services:
    pagination:
        class: GpsLab\Bundle\PaginationBundle\Service\Builder
        arguments: [ '@router', '%pagination.max_navigate%', '%pagination.parameter_name%' ]

    pagination.twig_extension:
        class: GpsLab\Bundle\PaginationBundle\Twig\Extension\PaginationExtension
        arguments: [ '%pagination.template%' ]
        tags:
            - { name: twig.extension }
